export const services = [
  {
    id: 1,
    name: "Khám tổng quát",
    price: 500000,
    duration: 30,
    specialtyId: "Khoa1",
  },
  {
    id: 2,
    name: "Khám tim mạch",
    price: 700000,
    duration: 45,
    specialtyId: "Khoa4",
  },
  {
    id: 3,
    name: "Khám tai mũi họng",
    price: 400000,
    duration: 25,
    specialtyId: "Khoa3",
  },
  {
    id: 4,
    name: "Khám mắt",
    price: 350000,
    duration: 20,
    specialtyId: "Khoa2",
  },
  {
    id: 5,
    name: "Khám nội tiết",
    price: 650000,
    duration: 40,
    specialtyId: "Khoa5",
  },
  {
    id: 6,
    name: "Khám da liễu",
    price: 300000,
    duration: 20,
    specialtyId: "Khoa6",
  },
  {
    id: 7,
    name: "Khám thần kinh",
    price: 800000,
    duration: 60,
    specialtyId: "Khoa2",
  },
  {
    id: 8,
    name: "Khám sản phụ khoa",
    price: 600000,
    duration: 40,
    specialtyId: "Khoa8",
  },
  {
    id: 9,
    name: "Khám hô hấp",
    price: 450000,
    duration: 30,
    specialtyId: "Khoa5",
  },
  {
    id: 10,
    name: "Khám tiêu hóa",
    price: 550000,
    duration: 35,
    specialtyId: "Khoa3",
  },
];
