const doctors = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    desc: "Bác sĩ nội tổng quát với hơn 10 năm kinh nghiệm.",
    shift: "Sáng",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:00",
    specialtyIds: ["Khoa1"],
    medical: { id: 1, name: "Trung Tâm Y Khoa Việt Đức" },
    phoneNumber: "0987654321",
    status: "active",
  },
  {
    id: 2,
    name: "Trần Thị B",
    desc: "Chuyên khoa thần kinh, giàu kinh nghiệm trong điều trị động kinh.",
    shift: "Chiều",
    schedule: "Thứ 2 - Thứ 7, 7:30 - 16:30",
    specialtyIds: ["Khoa2"],
    medical: { id: 2, name: "Bệnh Viện Bạch Mai" },
    phoneNumber: "0912345678",
    status: "active",
  },
  {
    id: 3,
    name: "Lê Văn C",
    desc: "Bác sĩ chuyên về tiêu hóa, nội soi và điều trị gan mật.",
    shift: "Tối",
    schedule: "Thứ 3 - Chủ Nhật, 9:00 - 18:00",
    specialtyIds: ["Khoa3"],
    medical: { id: 3, name: "Phòng Khám Đa Khoa Hoàn Mỹ" },
    phoneNumber: "0905123456",
    status: "inactive",
  },
  {
    id: 4,
    name: "Phạm Thị D",
    desc: "Bác sĩ tim mạch với kinh nghiệm phẫu thuật mạch vành.",
    shift: "Sáng",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:30",
    specialtyIds: ["Khoa4"],
    medical: { id: 5, name: "Bệnh Viện Trung Ương Huế" },
    phoneNumber: "0988112233",
    status: "active",
  },
  {
    id: 5,
    name: "Hoàng Văn E",
    desc: "Chuyên gia hô hấp, điều trị các bệnh phổi mãn tính.",
    shift: "Chiều",
    schedule: "Thứ 2 - Thứ 7, 7:00 - 15:00",
    specialtyIds: ["Khoa5"],
    medical: { id: 9, name: "Bệnh Viện Chợ Rẫy" },
    phoneNumber: "0977888999",
    status: "active",
  },
  {
    id: 6,
    name: "Đặng Thị F",
    desc: "Bác sĩ da liễu, chuyên về điều trị mụn và bệnh ngoài da.",
    shift: "Sáng",
    schedule: "Thứ 3 - Chủ Nhật, 8:30 - 17:00",
    specialtyIds: ["Khoa6"],
    medical: { id: 17, name: "Bệnh Viện Da Liễu Hà Nội" },
    phoneNumber: "0966333444",
    status: "inactive",
  },
  {
    id: 7,
    name: "Vũ Văn G",
    desc: "Bác sĩ nhi khoa, nhiều năm làm việc tại viện Nhi.",
    shift: "Chiều",
    schedule: "Thứ 2 - Thứ 6, 9:00 - 17:00",
    specialtyIds: ["Khoa7"],
    medical: { id: 13, name: "Bệnh Viện Nhi Trung Ương" },
    phoneNumber: "0955222111",
    status: "active",
  },
  {
    id: 8,
    name: "Ngô Thị H",
    desc: "Nhi khoa, chuyên tư vấn phát triển thể chất cho trẻ.",
    shift: "Sáng",
    schedule: "Thứ 2 - Thứ 7, 8:00 - 16:00",
    specialtyIds: ["Khoa7"],
    medical: { id: 13, name: "Bệnh Viện Nhi Trung Ương" },
    phoneNumber: "0944667788",
    status: "active",
  },
  {
    id: 9,
    name: "Phan Văn I",
    desc: "Bác sĩ cơ xương khớp, tập trung điều trị loãng xương.",
    shift: "Tối",
    schedule: "Thứ 4 - Chủ Nhật, 10:00 - 19:00",
    specialtyIds: ["Khoa1"],
    medical: { id: 1, name: "Trung Tâm Y Khoa Việt Đức" },
    phoneNumber: "0933556677",
    status: "inactive",
  },
  {
    id: 10,
    name: "Mai Thị K",
    desc: "Chuyên khoa thần kinh, điều trị đau nửa đầu.",
    shift: "Sáng",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:00",
    specialtyIds: ["Khoa2"],
    medical: { id: 2, name: "Bệnh Viện Bạch Mai" },
    phoneNumber: "0922334455",
    status: "active",
  },
];
export { doctors };
