const doctors = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    desc: "Bác sĩ nội tổng quát với hơn 10 năm kinh nghiệm.",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:00",
    specialty: { id: "Khoa1", name: "Cơ Xương Khớp" },
    medical: { id: 1, name: "Trung Tâm Y Khoa Việt Đức" },
    phoneNumber: "0987654321",
    status: "active",
  },
  {
    id: 2,
    name: "Trần Thị B",
    desc: "Chuyên khoa thần kinh, giàu kinh nghiệm trong điều trị động kinh.",
    schedule: "Thứ 2 - Thứ 7, 7:30 - 16:30",
    specialty: { id: "Khoa2", name: "Thần Kinh" },
    medical: { id: 2, name: "Bệnh Viện Bạch Mai" },
    phoneNumber: "0912345678",
    status: "active",
  },
  {
    id: 3,
    name: "Lê Văn C",
    desc: "Bác sĩ chuyên về tiêu hóa, nội soi và điều trị gan mật.",
    schedule: "Thứ 3 - Chủ Nhật, 9:00 - 18:00",
    specialty: { id: "Khoa3", name: "Tiêu Hóa" },
    medical: { id: 3, name: "Phòng Khám Đa Khoa Hoàn Mỹ" },
    phoneNumber: "0905123456",
    status: "inactive",
  },
  {
    id: 4,
    name: "Phạm Thị D",
    desc: "Bác sĩ tim mạch với kinh nghiệm phẫu thuật mạch vành.",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:30",
    specialty: { id: "Khoa4", name: "Tim Mạch" },
    medical: { id: 5, name: "Bệnh Viện Trung Ương Huế" },
    phoneNumber: "0988112233",
    status: "active",
  },
  {
    id: 5,
    name: "Hoàng Văn E",
    desc: "Chuyên gia hô hấp, điều trị các bệnh phổi mãn tính.",
    schedule: "Thứ 2 - Thứ 7, 7:00 - 15:00",
    specialty: { id: "Khoa5", name: "Hô Hấp" },
    medical: { id: 9, name: "Bệnh Viện Chợ Rẫy" },
    phoneNumber: "0977888999",
    status: "active",
  },
  {
    id: 6,
    name: "Đặng Thị F",
    desc: "Bác sĩ da liễu, chuyên về điều trị mụn và bệnh ngoài da.",
    schedule: "Thứ 3 - Chủ Nhật, 8:30 - 17:00",
    specialty: { id: "Khoa6", name: "Da Liễu" },
    medical: { id: 17, name: "Bệnh Viện Da Liễu Hà Nội" },
    phoneNumber: "0966333444",
    status: "inactive",
  },
  {
    id: 7,
    name: "Vũ Văn G",
    desc: "Bác sĩ nhi khoa, nhiều năm làm việc tại viện Nhi.",
    schedule: "Thứ 2 - Thứ 6, 9:00 - 17:00",
    specialty: { id: "Khoa7", name: "Nhi Khoa" },
    medical: { id: 13, name: "Bệnh Viện Nhi Trung Ương" },
    phoneNumber: "0955222111",
    status: "active",
  },
  {
    id: 8,
    name: "Ngô Thị H",
    desc: "Nhi khoa, chuyên tư vấn phát triển thể chất cho trẻ.",
    schedule: "Thứ 2 - Thứ 7, 8:00 - 16:00",
    specialty: { id: "Khoa7", name: "Nhi Khoa" },
    medical: { id: 13, name: "Bệnh Viện Nhi Trung Ương" },
    phoneNumber: "0944667788",
    status: "active",
  },
  {
    id: 9,
    name: "Phan Văn I",
    desc: "Bác sĩ cơ xương khớp, tập trung điều trị loãng xương.",
    schedule: "Thứ 4 - Chủ Nhật, 10:00 - 19:00",
    specialty: { id: "Khoa1", name: "Cơ Xương Khớp" },
    medical: { id: 1, name: "Trung Tâm Y Khoa Việt Đức" },
    phoneNumber: "0933556677",
    status: "inactive",
  },
  {
    id: 10,
    name: "Mai Thị K",
    desc: "Chuyên khoa thần kinh, điều trị đau nửa đầu.",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:00",
    specialty: { id: "Khoa2", name: "Thần Kinh" },
    medical: { id: 2, name: "Bệnh Viện Bạch Mai" },
    phoneNumber: "0922334455",
    status: "active",
  },
  {
    id: 11,
    name: "Nguyễn Văn L",
    desc: "Chuyên gia tiêu hóa, điều trị viêm loét dạ dày.",
    schedule: "Thứ 3 - Thứ 7, 7:30 - 16:30",
    specialty: { id: "Khoa3", name: "Tiêu Hóa" },
    medical: { id: 3, name: "Phòng Khám Đa Khoa Hoàn Mỹ" },
    phoneNumber: "0911002200",
    status: "active",
  },
  {
    id: 12,
    name: "Trần Thị M",
    desc: "Bác sĩ tim mạch, giàu kinh nghiệm trong điều trị suy tim.",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:30",
    specialty: { id: "Khoa4", name: "Tim Mạch" },
    medical: { id: 5, name: "Bệnh Viện Trung Ương Huế" },
    phoneNumber: "0933114455",
    status: "inactive",
  },
  {
    id: 13,
    name: "Lê Văn N",
    desc: "Chuyên khoa hô hấp, điều trị hen suyễn.",
    schedule: "Thứ 2 - Thứ 7, 7:00 - 15:00",
    specialty: { id: "Khoa5", name: "Hô Hấp" },
    medical: { id: 9, name: "Bệnh Viện Chợ Rẫy" },
    phoneNumber: "0988223344",
    status: "active",
  },
  {
    id: 14,
    name: "Phạm Thị O",
    desc: "Chuyên khoa da liễu, chăm sóc da thẩm mỹ.",
    schedule: "Thứ 3 - Chủ Nhật, 8:30 - 17:00",
    specialty: { id: "Khoa6", name: "Da Liễu" },
    medical: { id: 17, name: "Bệnh Viện Da Liễu Hà Nội" },
    phoneNumber: "0977445566",
    status: "active",
  },
  {
    id: 15,
    name: "Hoàng Văn P",
    desc: "Bác sĩ nhi khoa, tư vấn dinh dưỡng cho trẻ.",
    schedule: "Thứ 2 - Thứ 6, 9:00 - 17:00",
    specialty: { id: "Khoa7", name: "Nhi Khoa" },
    medical: { id: 13, name: "Bệnh Viện Nhi Trung Ương" },
    phoneNumber: "0955667788",
    status: "inactive",
  },
  {
    id: 16,
    name: "Đặng Thị Q",
    desc: "Chuyên khoa nội tổng quát, khám sức khỏe định kỳ.",
    schedule: "Thứ 2 - Thứ 7, 8:00 - 16:00",
    specialty: { id: "Khoa8", name: "Nội Tổng Quát" },
    medical: { id: 1, name: "Trung Tâm Y Khoa Việt Đức" },
    phoneNumber: "0911888999",
    status: "active",
  },
  {
    id: 17,
    name: "Vũ Văn R",
    desc: "Chuyên khoa thần kinh, điều trị mất ngủ.",
    schedule: "Thứ 4 - Chủ Nhật, 10:00 - 19:00",
    specialty: { id: "Khoa2", name: "Thần Kinh" },
    medical: { id: 2, name: "Bệnh Viện Bạch Mai" },
    phoneNumber: "0922113344",
    status: "inactive",
  },
  {
    id: 18,
    name: "Ngô Thị S",
    desc: "Bác sĩ cơ xương khớp, phục hồi chức năng.",
    schedule: "Thứ 2 - Thứ 6, 8:00 - 17:00",
    specialty: { id: "Khoa1", name: "Cơ Xương Khớp" },
    medical: { id: 1, name: "Trung Tâm Y Khoa Việt Đức" },
    phoneNumber: "0977665544",
    status: "active",
  },
  {
    id: 19,
    name: "Phan Văn T",
    desc: "Chuyên gia hô hấp, điều trị COPD.",
    schedule: "Thứ 2 - Thứ 7, 7:30 - 15:30",
    specialty: { id: "Khoa5", name: "Hô Hấp" },
    medical: { id: 9, name: "Bệnh Viện Chợ Rẫy" },
    phoneNumber: "0944556677",
    status: "active",
  },
  {
    id: 20,
    name: "Mai Thị U",
    desc: "Bác sĩ da liễu, điều trị bệnh vảy nến.",
    schedule: "Thứ 3 - Chủ Nhật, 9:00 - 18:00",
    specialty: { id: "Khoa6", name: "Da Liễu" },
    medical: { id: 17, name: "Bệnh Viện Da Liễu Hà Nội" },
    phoneNumber: "0988443322",
    status: "inactive",
  },
];

export { doctors };
